name: goreleaser-action

on:
  push:
    tags:
      - 'v*'

# permissions:
#   contents: read
#   packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Fetch all tags
        run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6 #https://github.com/goreleaser/goreleaser-action
        with:
          distribution: goreleaser
          version: "~> v2" # or 'latest', 'nightly', semver
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        #https://github.com/actions/upload-artifact
        with:
          name: go-olive
          # path: ./dist/* #全部文件一股脑打包，太臃肿
          path: |
            ./dist/*.tar.gz
            ./dist/*.zip
            ./dist/*checksums.txt



